---
title: "draft"
author: "Jincheng Wang"
date: "7/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Preparation
1. Setup
```{r setup, message=FALSE, warning=FALSE}
# Loading library here
library(knitr)
library(tidyverse)
library(readxl)
library(ggrepel)
library(rstatix)

options(max.print="75")
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, prompt=FALSE, tidy = TRUE, comment = NA, message = FALSE)
opts_knit$set(width=75)

# set path
opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
setwd(rprojroot::find_rstudio_root_file())
## path to data record on dropbox
path_rec <- "~/Dropbox/IFNH CSR/ExperimentRecords/"
list.files(path_rec)

# number of cores/thread to use
nc <- switch(Sys.info()[['sysname']], Windows = 1, Darwin = 4, Linux = 12)

source("code/utils.R")

BM_colors = c("#377EB8", "#4DAF4A", "#E41A1C", "purple")
names(BM_colors) = c("VF", "CSR", "CS", "VD")
sessionInfo()
```

## Body weight
### Overall, plotting all data
```{r}
BW <- read_excel(paste0(path_rec, "MasterMetadata-CS-SW-Oct2019-20210402-HS.xlsx"), sheet = "BodyWeightRecords", range = "A1:T2009") %>% filter(!is.na(Weight_g))
BW$BirthMode = factor(BW$BirthMode, levels = c("VF", "CSR", "CS"))

# BW <- BW %>% filter(!FamilyID %in% c("VF1", "CSR1") )
current_days <- max(BW$TimePoint_Days)

BW_sum <- BW %>% group_by(TimePoint_Days, BirthMode, Sex) %>% summarise(N = n(), Mean = mean(Weight_g), SE = sd(Weight_g)/sqrt(N))

y_max <- ceiling(max(BW$Weight_g)/4)*4
ggplot(BW, aes(x = TimePoint_Days, y = Weight_g, color = BirthMode)) +
    geom_point(size = 0.5, alpha = 0.5) +
    geom_path(aes(group = MouseNo), color = "grey", size = 0.5, alpha = 0.5) +
    geom_smooth(aes(fill = BirthMode), alpha = 0.3) +
    geom_text_repel(data = BW_sum, aes(x = TimePoint_Days, y = Mean, label = N), size = 4, show.legend = F) +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(7, current_days, 7)), labels = c(seq(7, current_days, 7))/7) + 
    scale_y_continuous(breaks = seq(2, y_max, 4)) +
    scale_color_manual(values = BM_colors) +
    scale_fill_manual(values = BM_colors) +
    labs(x = "Sampling_Week", y = "Body Weight(g)", title = "C-Section Restoration Project - Body Weight Plots-AllData") +
    theme_jw() + theme(panel.grid.minor = element_blank())
```

### Summary table
```{r}
BW_sum2 <- BW %>% group_by(TimePoint_Weeks, BirthMode, Sex) %>% summarise(N = n(), N_batch = unique(Batch) %>% length, N_family = unique(FamilyNo) %>% length(), Mean = mean(Weight_g), SE = sd(Weight_g)/sqrt(N))

BW_sum2 %>% mutate(Count = paste0(N, "(", N_family, ")")) %>% select(BirthMode, Sex, TimePoint_Weeks, Count) %>% spread(key = TimePoint_Weeks, value = Count)
```

### Detailed plot
```{r}
#date_range <- c(2, BW_sum2$TimePoint_Weeks[BW_sum2$N_family>=5] %>% max)
date_range <- seq(3, 15, by = 1)

BW_dat <- BW %>% dplyr::filter(TimePoint_Weeks %in% date_range)

BW_dat_sum <- BW_dat %>% group_by(TimePoint_Weeks, BirthMode, Sex) %>% summarise(Mean_cl = Hmisc::smean.cl.normal(x = Weight_g) %>% paste(collapse = "-"), N = n()) %>% separate(Mean_cl, into = c("Mean", "Lwr", "Uwr"), sep = "-", convert = T) %>% ungroup

ggplot(BW_dat, aes(x = TimePoint_Weeks, y = Weight_g, color = BirthMode)) +
    geom_smooth(aes(fill = BirthMode), alpha = 0.3) +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) + 
    scale_color_manual(values = BM_colors) +
    scale_fill_manual(values = BM_colors) +
    labs(x = "Sampling_Week", y = "Body Weight(g)", title = "IFNHCSR-BodyWeight", subtitle = str_wrap("LOESS smooth with 95% CI", width = 120)) +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.8, plot.title = element_text(hjust = 0))
set_panel_size(file = "results/figs/exploratory/BW_smooth.pdf", width = unit(3, "in"), height = unit(2.4, "in"))



BW_dat_stat <- BW_dat %>% group_by(TimePoint_Weeks, Sex) %>% t_test(Weight_g~BirthMode) %>% mutate(p.adj = p.adjust(p, "fdr") %>% round(., 3), p = round(p, 3))

p = ggplot(BW_dat_sum, aes(x = TimePoint_Weeks, y = Mean, color = BirthMode)) +
    geom_point(data = BW_dat, aes(y = Weight_g), size = 0.5, alpha = 0.5) +
    geom_path(data = BW_dat, aes(y = Weight_g, group = MouseNo), color = "grey", size = 0.5, alpha = 0.5) +
    geom_ribbon(aes(y = Mean, ymin = Lwr, ymax = Uwr, fill = BirthMode), alpha = 0.4, color = NA) +
    geom_point(size = 1.5) +
    geom_line() +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) + 
    scale_color_manual(values = BM_colors) +
    scale_fill_manual(values = BM_colors) +
    labs(x = "Sampling_Week", y = "Body Weight (g)", title = "IFNHCSR - Body Weight", subtitle = str_wrap("Mean and 95% CI were plotted.", width = 120)) +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.8, plot.title = element_text(hjust = 0))
print(p)
set_panel_size(file = "results/figs/exploratory/BW_mean_ci.pdf", width = unit(3, "in"), height = unit(2.4, "in"))

ggplot(BW_dat_stat, aes(x = TimePoint_Weeks, y = p.adj, color = paste(group1, group2, sep = "-"))) +
    geom_point() +
    geom_line() +
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "black") +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) +
    scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3')) +
    labs(x = "Sampling_Week", y = "FDR adjusted p-value", title = "IFNHCSR - P-value for body weight", color = "Comparison") +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.8, plot.title = element_text(hjust = 0))
set_panel_size(file = "results/figs/exploratory/BW_p_fdr.pdf", width = unit(3, "in"), height = unit(2.1, "in"))

```

## Body Weight gain relative to week 3 all data
```{r}
BW_f <- BW %>% group_by(MouseID) %>% filter(n()>1, 3 %in% TimePoint_Weeks) %>% ungroup() %>% filter(TimePoint_Weeks>=3) %>% arrange(TimePoint_Weeks) %>% group_by(MouseID) %>% mutate(Weight_gain = (Weight_g - Weight_g[1])/Weight_g[1]*100, BirthMode = factor(BirthMode, levels = c("VF", "CSR", "CS")))
BW_f %>% ungroup() %>% pivot_wider(id_cols = c(BirthMode, MouseID), names_from = TimePoint_Weeks, values_from = Weight_gain)


date_range = seq(4, 15, by = 1)

BW_f_2 <- BW_f %>% filter(TimePoint_Weeks %in% date_range)
BW_f_2 %>% group_by(TimePoint_Weeks, BirthMode, Sex) %>% summarise(N = n()) %>% pivot_wider(id_cols = c(BirthMode, Sex), names_from = TimePoint_Weeks, values_from = N)

ggplot(BW_f_2, aes(x = TimePoint_Weeks, y = Weight_gain, color = BirthMode)) +
    geom_smooth(aes(fill = BirthMode), alpha = 0.3) +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) + 
    scale_color_manual(values = BM_colors) +
    scale_fill_manual(values = BM_colors) +
    labs(x = "Sampling_Week", y = "Body Weight Gain(%)", title = "IFNHCSR - Body Weight Gain", subtitle = str_wrap("LOESS smooth with 95% CI", width = 120)) +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.7, plot.title = element_text(hjust = 0))
set_panel_size(file = "results/figs/exploratory/BW_gain_smooth.pdf", width = unit(3, "in"), height = unit(2.1, "in"))

BW_f_2_sum <- BW_f_2 %>% group_by(TimePoint_Weeks, BirthMode, Sex) %>% summarise(Mean_cl = Hmisc::smean.cl.normal(x = Weight_gain) %>% paste(collapse = "/"), N = n()) %>% separate(Mean_cl, into = c("Mean", "Lwr", "Uwr"), sep = "/", convert = T) %>% ungroup

BW_f_2_sum %>% pivot_wider(id_cols = c(BirthMode, Sex), names_from = TimePoint_Weeks, values_from = N)

BW_f_2_stat <- BW_f_2 %>% group_by(TimePoint_Weeks, Sex) %>% t_test(Weight_gain~BirthMode) %>% ungroup() %>% mutate(p.adj = p.adjust(p, "fdr") %>% round(., 3), p = round(p, 3)) 

BW_f_2_stat_sum <- (BW_f_2_stat %>% pivot_wider(id_cols = c(Sex, group1, group2), names_from = TimePoint_Weeks, values_from = p))[c(2, 3, 1, 5, 6, 4), ] %>% unite(Compare, group1, group2, sep = "-") 

p = ggplot(BW_f_2_sum, aes(x = TimePoint_Weeks, y = Mean, color = BirthMode)) +
    geom_point(data = BW_f_2, aes(y = Weight_gain), size = 0.5, alpha = 0.5) +
    geom_path(data = BW_f_2, aes(y = Weight_gain, group = MouseNo), color = "grey", size = 0.5, alpha = 0.5) +
    geom_ribbon(aes(y = Mean, ymin = Lwr, ymax = Uwr, fill = BirthMode), alpha = 0.4, color = NA) +
    geom_point(size = 1.5) +
    geom_line() +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) + 
    scale_color_manual(values = BM_colors) +
    scale_fill_manual(values = BM_colors) +
    labs(x = "Sampling_Week", y = "Body Weight Gain(%)", title = "IFNHCSR - Body Weight Gain", subtitle = str_wrap("Mean and 95% CI were plotted.", width = 120)) +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.8, plot.title = element_text(hjust = 0))
print(p)
set_panel_size(file = "results/figs/exploratory/BW_gain_mean_ci.pdf", width = unit(3, "in"), height = unit(2.1, "in"))

ggplot(BW_f_2_stat, aes(x = TimePoint_Weeks, y = p.adj, color = paste(group1, group2, sep = "-"))) +
    geom_point() +
    geom_line() +
    geom_hline(yintercept = 0.05, linetype = "dashed", color = "black") +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) +
    scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3')) +
    labs(x = "Sampling_Week", y = "FDR adjusted p-value", title = "IFNHCSR - P-value for body weight gain", color = "Comparison") +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.8, plot.title = element_text(hjust = 0))
set_panel_size(file = "results/figs/exploratory/BW_gain_p_fdr.pdf", width = unit(3, "in"), height = unit(2.1, "in"))

```
## Responders vs Non-responders
```{r}
n_sd = 1

BW_f_vf_range = BW_f %>% ungroup %>% filter(BirthMode=="VF") %>% group_by(Sex, TimePoint_Weeks) %>% summarise(summ = Hmisc::smean.sdl(Weight_g, mult = n_sd) %>% paste(collapse = ";")) %>% separate(summ, into = c("vf_mean", "vf_ll", "vf_ul"), sep = ";")

BW_f_3 = merge(BW_f, BW_f_vf_range, by = c("Sex", "TimePoint_Weeks")) %>% filter(TimePoint_Weeks<=15) %>% mutate(Flag = ifelse(Weight_g > vf_ul, "Overweight", ifelse(Weight_g < vf_ll, "Underweight", "Normal")))

ggplot(BW_f_3 %>% mutate(BirthMode = factor(BirthMode, levels = c("CS", "CSR", "VF"))), aes(x = TimePoint_Weeks, y = Weight_g)) +
    geom_point(size = 1, aes(color = Flag)) +
    geom_line(aes(group = MouseID, color = Flag), size = 0.3) +
    stat_summary(data = BW_f_3 %>% filter(BirthMode=="VF") %>% select(-BirthMode), geom = "ribbon", fun.data = "mean_sdl", fun.args = list(mult = n_sd), fill = "#377EB8", alpha = 0.2) +
    stat_summary(data = BW_f_3 %>% filter(BirthMode=="VF") %>% select(-BirthMode), geom = "line", fun = "mean", color = "#377EB8", size = 2) +
    annotate("segment", x=-Inf, xend = Inf, y = -Inf, yend = -Inf) +
    #stat_summary(data = BW_f %>% filter(BirthMode=="CS") %>% select(-BirthMode), geom = "ribbon", fun.data = "mean_sdl", fun.args = list(mult = n_sd), fill = "#E41A1C", alpha = 0.3) +
    #stat_summary(data = BW_f %>% filter(BirthMode=="CS") %>% select(-BirthMode), geom = "line", fun.y = "mean", color = "#E41A1C", size = 1) +
    facet_grid(Sex ~ BirthMode) +
    scale_color_manual(values = c("Overweight" = "red", "Normal" = "grey30", "Underweight" = "green")) +
    theme_jw(base_size = 18) + theme(aspect.ratio = 0.8) +
    scale_x_continuous(breaks = seq(4, 15, 2)) +
    labs(x = "Weeks", y = "Body Weight (g)")


BW_f_3_or_dat <- BW_f_3 %>% group_by(Sex, BirthMode, MouseID) %>% filter(TimePoint_Weeks>=6) %>% summarise(N = n(), Pct_over = sum(Flag=="Overweight")/N, Pct_under = sum(Flag=="Underweight")/N) %>% mutate(Over = Pct_over>=0.7, Under = Pct_under>=0.7) %>% group_by(Sex, BirthMode) %>% summarise(N_sub = n(), N_over = sum(Over), N_under = sum(Under)) %>% ungroup() 

BW_f_3_or <- BW_f_3_or_dat %>% split(., .$Sex) %>% lapply(., function(y){y %>% mutate(N_normal = N_sub - N_over - N_under) %>% select(BirthMode, N_normal, N_over) %>% column_to_rownames(var = "BirthMode") %>% as.matrix() %>% oddsratio.fisher()})

lapply(BW_f_3_or, function(x){merge(merge(as.data.frame(x$data)[1:3, 1:2], as.data.frame(x$measure), by = 0), as.data.frame(x$p.value)[2], by.x = 1, by.y = 0)}) %>% data.table::rbindlist(idcol = "Sex")

```

```{r}
n_sd = 1

BW_f_vf_range = BW_f %>% ungroup %>% filter(BirthMode=="VF") %>% group_by(Sex, TimePoint_Weeks) %>% summarise(summ = Hmisc::smean.sdl(Weight_gain, mult = n_sd) %>% paste(collapse = ";")) %>% separate(summ, into = c("vf_mean", "vf_ll", "vf_ul"), sep = ";", convert = T)

BW_f_4 = merge(BW_f, BW_f_vf_range, by = c("Sex", "TimePoint_Weeks")) %>% ungroup %>% filter(TimePoint_Weeks<=15) %>% mutate(Flag = ifelse(Weight_gain > vf_ul, "Overweight", ifelse(Weight_gain < vf_ll, "Underweight", "Normal")))

ggplot(BW_f_4 %>% mutate(BirthMode = factor(BirthMode, levels = c("CS", "CSR", "VF"))), aes(x = TimePoint_Weeks, y = Weight_gain)) +
    geom_point(size = 1, aes(color = Flag)) +
    geom_line(aes(group = MouseID, color = Flag), size = 0.3) +
    stat_summary(data = BW_f_4 %>% filter(BirthMode=="VF") %>% select(-BirthMode), geom = "ribbon", fun.data = "mean_sdl", fun.args = list(mult = n_sd), fill = "#377EB8", alpha = 0.2) +
    stat_summary(data = BW_f_4 %>% filter(BirthMode=="VF") %>% select(-BirthMode), geom = "line", fun = "mean", color = "#377EB8", size = 2) +
    annotate("segment", x=-Inf, xend = Inf, y = -Inf, yend = -Inf) +
    #stat_summary(data = BW_f %>% filter(BirthMode=="CS") %>% select(-BirthMode), geom = "ribbon", fun.data = "mean_sdl", fun.args = list(mult = n_sd), fill = "#E41A1C", alpha = 0.3) +
    #stat_summary(data = BW_f %>% filter(BirthMode=="CS") %>% select(-BirthMode), geom = "line", fun.y = "mean", color = "#E41A1C", size = 1) +
    facet_grid(Sex ~ BirthMode) +
    scale_color_manual(values = c("Overweight" = "red", "Normal" = "grey30", "Underweight" = "green")) +
    theme_jw(base_size = 18) + theme(aspect.ratio = 0.8) +
    scale_x_continuous(breaks = seq(4, 15, 2)) +
    labs(x = "Weeks", y = "Body Weight gain(% to week 3 body weight)")


BW_f_4_or_dat <- BW_f_4 %>% group_by(Sex, BirthMode, MouseID) %>% filter(TimePoint_Weeks>=6) %>% summarise(N = n(), Pct_over = sum(Flag=="Overweight")/N, Pct_under = sum(Flag=="Underweight")/N) %>% mutate(Over = Pct_over>=0.7, Under = Pct_under>=0.7) %>% group_by(Sex, BirthMode) %>% summarise(N_sub = n(), N_over = sum(Over), N_under = sum(Under)) %>% ungroup() 

BW_f_4_or <- BW_f_4_or_dat %>% split(., .$Sex) %>% lapply(., function(y){y %>% mutate(N_normal = N_sub - N_over - N_under) %>% select(BirthMode, N_normal, N_over) %>% column_to_rownames(var = "BirthMode") %>% as.matrix() %>% oddsratio.fisher()})

lapply(BW_f_4_or, function(x){merge(merge(as.data.frame(x$data)[1:3, 1:2], as.data.frame(x$measure), by = 0), as.data.frame(x$p.value)[2], by.x = 1, by.y = 0)}) %>% data.table::rbindlist(idcol = "Sex")
```

## Body Weight gain relative to week 3 pre-covid
```{r}
BW_f <- BW %>% group_by(MouseID) %>% filter(n()>1, 3 %in% TimePoint_Weeks, !Batch %in% c("Batch9", "Batch10")) %>% ungroup() %>% filter(TimePoint_Weeks>=3) %>% arrange(TimePoint_Weeks) %>% group_by(MouseID) %>% mutate(Weight_gain = (Weight_g - Weight_g[1])/Weight_g[1]*100, BirthMode = factor(BirthMode, levels = c("VF", "CSR", "CS")))
BW_f %>% ungroup() %>% pivot_wider(id_cols = c(BirthMode, MouseID), names_from = TimePoint_Weeks, values_from = Weight_gain)

date_range = seq(4, 15, by = 1)

BW_f_2 <- BW_f %>% filter(TimePoint_Weeks %in% date_range)
BW_f_2 %>% group_by(TimePoint_Weeks, BirthMode, Sex) %>% summarise(N = n()) %>% pivot_wider(names_from = c(BirthMode, Sex), values_from = N)

ggplot(BW_f_2, aes(x = TimePoint_Weeks, y = Weight_gain, color = BirthMode)) +
    geom_smooth(aes(fill = BirthMode), alpha = 0.3) +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) + 
    scale_color_manual(values = BM_colors) +
    scale_fill_manual(values = BM_colors) +
    labs(x = "Sampling_Week", y = "Body Weight Gain(%)", title = "IFNHCSR - Body Weight Gain", subtitle = str_wrap("LOESS smooth with 95% CI", width = 120)) +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.7, plot.title = element_text(hjust = 0))
set_panel_size(file = "results/figs/exploratory/BW_gain_smooth_precovid.pdf", width = unit(3, "in"), height = unit(2.1, "in"))

BW_f_2_sum <- BW_f_2 %>% group_by(TimePoint_Weeks, BirthMode, Sex) %>% summarise(Mean_cl = Hmisc::smean.cl.normal(x = Weight_gain) %>% paste(collapse = "-"), N = n()) %>% separate(Mean_cl, into = c("Mean", "Lwr", "Uwr"), sep = "-", convert = T) %>% ungroup

BW_f_2_sum %>% pivot_wider(id_cols = c(BirthMode, Sex), names_from = TimePoint_Weeks, values_from = N) %>% View()

BW_f_2_stat <- BW_f_2 %>% group_by(TimePoint_Weeks, Sex) %>% t_test(Weight_gain~BirthMode) %>% ungroup() %>% mutate(p.adj = p.adjust(p, "fdr") %>% round(., 3), p = round(p, 3)) 

BW_f_2_stat_sum <- (BW_f_2_stat %>% pivot_wider(id_cols = c(Sex, group1, group2), names_from = TimePoint_Weeks, values_from = p))[c(2, 3, 1, 5, 6, 4), ] %>% unite(Compare, group1, group2, sep = "-") 

p = ggplot(BW_f_2_sum, aes(x = TimePoint_Weeks, y = Mean, color = BirthMode)) +
    geom_point(data = BW_f_2, aes(y = Weight_gain), size = 0.5, alpha = 0.5) +
    geom_path(data = BW_f_2, aes(y = Weight_gain, group = MouseNo), color = "grey", size = 0.5, alpha = 0.5) +
    geom_ribbon(aes(y = Mean, ymin = Lwr, ymax = Uwr, fill = BirthMode), alpha = 0.4, color = NA) +
    geom_point(size = 1.5) +
    geom_line() +
    facet_grid(.~Sex) +
    scale_x_continuous(breaks = c(seq(2, 18, 1))) + 
    scale_color_manual(values = BM_colors) +
    scale_fill_manual(values = BM_colors) +
    labs(x = "Sampling_Week", y = "Body Weight Gain(%)", title = "IFNHCSR - Body Weight Gain", subtitle = str_wrap("Mean and 95% CI were plotted.", width = 120)) +
    theme_jw() + theme(panel.grid.minor = element_blank(), aspect.ratio = 0.8, plot.title = element_text(hjust = 0))
print(p)
set_panel_size(file = "results/figs/exploratory/BW_gain_mean_ci_precovid.pdf", width = unit(3, "in"), height = unit(2.1, "in"))

```
## DEXA
```{r}
MM <- read_excel(paste0(path_rec, "MasterMetadata-CS-SW-Oct2019-20200701-JW.xlsx"), sheet = "MouseMetadata")

MM_dexa <- MM %>% filter(ExperimentSet=="Set1-BW", ReasonTermination %in% c("DEXA", "Week18Termination")) %>% mutate(TimePoint_Weeks = ifelse(ReasonTermination=="DEXA", 6, 18))



MM_dexa %>% group_by(TimePoint_Weeks, BirthMode, Sex) %>% summarise(N_family = length(unique(FamilyID)), N = length(unique(MouseID))) %>% mutate(Count = paste0(N, " (", N_family, ")")) %>% select(BirthMode, Sex, TimePoint_Weeks, Count) %>% spread(key = TimePoint_Weeks, value = Count) %>% View

spread(key = Sex, value = N)
```

## Behavior
```{r}
Beh <- read_excel(paste0(path_rec, "BehaviorAnimalMetadata-20190124-JW.xlsx"))

Beh %>% filter(Batch != "NA") %>% group_by(BirthMode, Sex) %>% summarise(N_family = length(unique(FamilyID)), N = length(unique(MouseNo))) %>%  mutate(Count = paste0(N, " (", N_family, ")")) 
```

## Feces

```{r}
MM <- read_excel(paste0(path_rec, "MasterMetadata-CS-SW-Oct2019-20200701-JW.xlsx"), sheet = "SampleMetadata")
MM_fec <- MM %>% filter(BodySite=="Feces")
MM_fec$TimePointInWeeks[MM_fec$TimePointInWeeks %in% c(11, 14)] = "11/14"

MM_fec %>% group_by(TimePointInWeeks, BirthMode, Sex) %>% summarise(N_family = length(unique(FamilyID)), N = length(unique(MouseID))) %>% mutate(Count = paste0(N, " (", N_family, ")")) %>% select(BirthMode, Sex, TimePointInWeeks, Count) %>% spread(key = TimePointInWeeks, value = Count) %>% View
```

## Sac
```{r}
MM <- read_excel(paste0(path_rec, "MasterMetadata-CS-SW-Oct2019-20200701-JW.xlsx"), sheet = "SampleMetadata")
Sac <- MM %>% filter(!SampleType %in% c("Feces", "Empty"))
Sac$BirthMode[Sac$BirthMode=="VD"] <- "VF"

Sac %>% group_by(TimePointInWeeks, BirthMode, Sex) %>% summarise(N_family = length(unique(FamilyID)), N = length(unique(MouseID))) %>% mutate(Count = paste0(N, " (", N_family, ")")) %>% select(BirthMode, Sex, TimePointInWeeks, Count) %>% spread(key = TimePointInWeeks, value = Count) %>% View

```


